# Generated by Django 5.1.3 on 2024-12-26 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teretana', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workoutplan',
            name='title',
        ),
        migrations.AddField(
            model_name='clanstvo',
            name='name',
            field=models.CharField(default='Default Name', max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plantreninga',
            name='name',
            field=models.CharField(default='Default Name', max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workoutplan',
            name='name',
            field=models.CharField(default='Default Name', max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='exercise',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='trening',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='vjezba',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
